site_name: OpenPages AI Bootcamp
site_url: https://farhan-ra.github.io/Openpages-AI-Bootcamp/
nav:
  - Home: index.md
  - Chapter 1: 
    - Overview: chapter1_prompt_basics/index.md
  - Chapter 2: 
    - Overview: chapter2_intermediate/index.md
    - Creating the model: chapter2_intermediate/wxai.md
    - Integrate the model in OpenPages: chapter2_intermediate/op_integration.md
    - Making the AI feature available in OpenPages: chapter2_intermediate/view_customisation.md
theme:
  name: material
  palette:
    primary: blue
    accent: light blue
extra_css:
  - assets/css/custom.css
