site_name: OpenPages AI Bootcamp
site_url: https://farhan-ra.github.io/Openpages-AI-Bootcamp/

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/ibm-logo.svg
  # favicon: assets/images/favicon.ico
  palette:
    - scheme: default
      primary: grey
      accent: blue
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    # - navigation.expand
    # - navigation.sections
    - search.highlight
    - search.share
    - content.code.copy
    - toc.integrate

nav:
  - Home: index.md
  - Chapter 1: 
    - Overview: chapter1/index.md
  - Chapter 2: 
    - Overview: chapter2/0_index.md
    - Creating the model: chapter2/1_wxai.md
    - Integrate the model in OpenPages: chapter2/2_op_integration.md
    - Making the AI feature available in OpenPages: chapter2/3_view_customisation.md
  - Chapter 3:
    - Overview: chapter3/0_index.md
    - Modifying an Object in OpenPages: chapter3/1_modify_op_object.md
    - Set-up and Integrate AI Model: chapter3/2_set_up_and_integrate_ai.md
    - Execute AI in Bulk: chapter3/3_bulk_analysis.md
  - Chapter 4:
    - Overview: chapter4/0_index.md
    - Configuring a Custom View as Input for ML Models: chapter4/1_configure_view_input.md
    - Validate the View Input: chapter4/2_validate_view_input.md
    - Develop and Deploy Prompt: chapter4/3_prompt.md
    - Integrate ML Model and Make Available in View: chapter4/4_integrate.md

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/sidebar-toggle.js
  - assets/js/scroll-flush-top.js
  - assets/js/toc-active-middle.js
  - assets/js/sidebar-state.js