site_name: OpenPages AI Bootcamp
nav:
  - Home: index.md
  - Chapter 1: 
    - Overview: chapter1_prompt_basics/index.md
  - Chapter 2: 
    - Overview: chapter2_intermediate/index.md
  - Chapter 3: chapter3_advanced/index.md
  - Chapter 4: chapter4_integration/index.md
  - Chapter 5: chapter5_governance/index.md
theme:
  name: material
  palette:
    primary: blue
    accent: light blue
extra_css:
  - assets/css/custom.css
