site_name: OpenPages AI Bootcamp
site_url: http://farhan-ra.github.io/Openpages-AI-Bootcamp
nav:
  - Home: index.md
  - Chapter 1: 
    - Overview: chapter1_prompt_basics/index.md
  - Chapter 2: 
    - Overview: chapter2_intermediate/index.md
theme:
  name: material
  palette:
    primary: blue
    accent: light blue
extra_css:
  - assets/css/custom.css
