site_name: OpenPages AI Bootcamp
site_url: https://farhan-ra.github.io/Openpages-AI-Bootcamp/
nav:
  - Home: index.md
  - Chapter 1: 
    - Overview: chapter1_prompt_basics/index.md
  - Chapter 2: 
    - Overview: chapter2_intermediate/index.md
    - Creating the model: chapter2_intermediate/wxai.md
    - Integrate the model in OpenPages: chapter2_intermediate/op_integration.md
    - Making the AI feature available in OpenPages: chapter2_intermediate/view_customisation.md
  - Chapter 3:
    - Overview: chapter3_advanced/index.md
    - Modifying an Object in OpenPages: chapter3_advanced/1_modify_op_object.md
    - Set-up and Integrate AI Model: chapter3_advanced/2_set_up_and_integrate_ai.md
    - Execute AI in Bulk: chapter3_advanced/3_bulk_analysis.md
theme:
  name: material
  palette:
    primary: blue
    accent: light blue
extra_css:
  - assets/css/custom.css
